### ISSUE TITLE
unwanted ; appended at the end of some messages when using quotes

### ISSUE THREAD

**Issue by suprememoocow** [gitterHQ/marked#2]
As reported by @fkautz at https://github.com/gitterHQ/gitter/issues/612:

Example output: in each case, no ; was ever typed:
"one"
"github.com/example/two";
"one.two/three";
"http://github.com/example/one"

The problem appears to be that "github.com/example/two" becomes `&quot;github.com/example/two&quot;`, which then gets incorrectly autolinked to `&quot;<a href="....">github.com/example/two&quot</a>;`

**Comment by lerouxb** [comment]
I merged in the pull request. This will be fixed in the main app as soon as I do a release.
