### ISSUE TITLE
Underscore pairs not getting removed when used multiple times

### ISSUE THREAD

**Issue by MadLittleMods** [gitterHQ/marked#4]
As reported by @vermiculus gitterHQ/gitter#767

Problem Example:
- Input: `this _is_ a _test_`
- Output: `<p>this <em>is_ a _test</em></p>`

Single usage (as expected):
- Input: `foo _bar_ baz`
- Output: `<p>foo <em>bar</em> baz</p>`

**Comment by vermiculus** [comment]
:+1:

**Comment by holtzermann17** [comment]
`:chart_with_upwards_trend: followed by _emphasized text_`

:chart_with_upwards_trend: followed by _emphasized text_

**Comment by tillig** [comment]
I added a PR for all but the use case reported by @holtzermann17. Hopefully this will help.

**Comment by grahamperrin** [comment]
> … (works here but not in gitter)

Now works in Gitter: https://gitter.im/gitterHQ/sandbox?at=593411c2e531dbc905acb902
